### ISSUE TITLE
Rename master view

### ISSUE THREAD

**Issue by ergonomicus** [evercode1/view-maker#3]
Just a proposal. Maybe it would be better if master.blade.php was named app.blade.php and avoid renaming?

Also, instead of breaking execution when layouts folder is found, maybe it would be better if user was prompted to overwrite existing layouts/app.blade.php?

**Comment by evercode1** [comment]
Actually, you can name your master page anything you want, calling it master is just a suggestion.  You can call it app, which will result in app.blade.php, but then you may run into problems when running make:auth.   When I get to a refinement phase, I will look at doing your second suggestion about allowing them to overwrite the file because I know we can provide feedback to the user and give them a choice.  That would probably be a better user experience, seems like it would be important, since you are already asking for it.
